### ISSUE TITLE
Node labels of agent nodes are not set

### ISSUE THREAD

**Issue by bk201** [rancher/rancherd#4] opened 2021-07-19 13:10 UTC
In Harvester we need all nodes to have `harvesterhci.io/managed=true` label. So for a bootstrap role, I use the following config:

```
node1:~ # cat /etc/rancher/rancherd/config.yaml
server: https://10.10.0.11:8443
role: agent
token: aaa
kubernetesVersion: v1.21.2+rke2r1
labels:
 - harvesterhci.io/managed=true
```

After bootstrapping, the node has corresponding labels and the RKE2 config looks right:

```
node1:~ # cat /etc/rancher/rke2/config.yaml.d/40-rancherd.yaml
node-label:
- harvesterhci.io/managed=true
token: aaa
```

But for agent role, if I join a cluster with the following config:

```
node2:~ # cat /etc/rancher/rancherd/config.yaml
server: https://10.10.0.11:8443
role: agent
token: aaa
kubernetesVersion: v1.21.2+rke2r1
labels:
 - harvesterhci.io/managed=true
```

The new agent nodes are not labelled. And the RKE2 config of label things is missing:

```
node2:~ # cat /etc/rancher/rke2/config.yaml.d/40-rancherd.yaml
{}
```

It looks like the [labels config is only carried in `cluster-init` role](https://github.com/rancher/rancherd/blob/cbed174fdd7e422a867db80aae46ea1a57f5048b/pkg/runtime/role.go#L54-L56),  did I use the wrong method to set labels?

**Comment by bk201** [comment] 2021-08-07 05:17
As a workaround, I created a file `/etc/rancher/rke2/config.yaml.d/90-harvester-agent.yaml` to append additional labels:

```
$ cat /etc/rancher/rke2/config.yaml.d/90-harvester-agent.yaml
node-label+:
 - harvesterhci.io/managed=true
```

**Comment by dereknola** [comment] 2021-09-07 20:57
Labels for agent nodes will not appear in `rancherd` as an agent does not write configuration. Also, node labels are available on agent nodes in the `rancher` yaml config.
```
root@node-2-buster64:/home/vagrant# cat /etc/rancher/rancherd/config.yaml 
server: https://192.168.1.231:8443
role: agent
token: '12345'
kubernetesVersion: v1.21.4+rke2r2
runtimeInstallerImage: dereknola/system-agent-installer-rke2
labels:
- harvesterhci.io/managed=true


root@node-2-buster64:/home/vagrant# cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml 
{
  "node-label": [
    "harvesterhci.io/managed=true",
    "rke.cattle.io/machine=fcd8e85d-40d3-4c62-bce1-0440a3ce2ae6"
  ],
  "server": "https://192.168.1.231:9345",
  "token": "12345"
}
```

**Comment by guangbochen** [comment] 2021-09-08 05:39
Hi @ibuildthecloud, since this PR is not needed https://github.com/rancher/rancherd/pull/6, can u please help to explain a little more about how can we address this issue properly, thanks.

**Comment by cjellick** [comment] 2021-09-08 14:49
I'm unassigning derek from this issue. Will have to be worked out between @guangbochen and @ibuildthecloud

**Comment by Jono-SUSE-Rancher** [comment] 2021-09-09 17:15
@guangbochen I assigned this to you for now. Could you sync up with @ibuildthecloud and see what (if anything) needs to be done on the Rancher side for this?

**Comment by ibuildthecloud** [comment] 2021-09-20 05:08
@bk201 rancherd only bootstraps a node once and the labels must be in ` /etc/rancher/rancherd/config.yaml` at that time.  If you change the config.yaml after the fact no changes will take effect.  Once the node is bootstrapped it is intended that all changes be made from rancher and/or in k8s.  If you wish to add a node label after the fact you should just add it the k8s v1.Node.

Is this the situation? I don't see any an issue with adding node labels when a worker node joins.

**Comment by bk201** [comment] 2021-09-24 00:53
@ibuildthecloud When bootstrapping an agent node, the agent node doesn't apply the labels specified in `/etc/rancher/rancherd/config.yaml`.
Like Derek's [fix](https://github.com/rancher/rancherd/pull/6/files), he tries to also apply labels on agent nodes.

Harvester needs to know if a node is managed by it by checking the `harvesterhci.io/managed=true` label and we want to do it in the installer stage. I think it's a bit inappropriate to add a controller to label every node we can see.

**Comment by ibuildthecloud** [comment] 2021-09-24 00:55
@bk201 how do you reproduce this as I tried this use case and it seemed to work for me.

**Comment by bk201** [comment] 2021-09-24 01:04
@ibuildthecloud Let me verify it again and see if it's already fixed.

**Comment by bk201** [comment] 2021-09-24 01:36
@ibrokethecloud I check again and found the labels are applied on agent nodes. I think I didn't check the `50-rancher.yaml` file or something is not correct atm. The issue doesn't exist in the first place. Sorry for the trouble.

**Closed** 2021-09-24 01:37 UTC
Labels: [zube]: Need Info
